version: '2'
services:
  elasticsearch:
    image: elasticsearch:latest
    ports:
      - "9200:9200"
      - "9300:9300"
  logstash:
    build: logstash/
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./logstash/config:/etc/logstash/conf.d
    ports:
      - "5000:5000"
    links:
      - elasticsearch
    networks:
      - server-net
  kibana:
    build: kibana/
    volumes:
      - ./kibana/config/:/opt/kibana/config/
    ports:
      - "5601:5601"
    links:
      - elasticsearch
    networks:
      - access-net
networks:
  server-net:
    ipam:
      config:
        - subnet: 10.0.0.0/16
          ip_range: 10.0.10.0/24
  access-net:
    ipam:
      config:
        - subnet: 192.168.0.0/16
          ip_range: 192.168.10.0/24
